### ISSUE TITLE
Returns error when running.

### ISSUE THREAD

**Issue by Zedwill96** [biggestcookie/Pokemon-py#26]
Traceback (most recent call last):
  File "C:\Users\Wesley Scott\Desktop\Pokemon-py-master\app.py", line 1, in <module>
    from game.player import PLAYER
  File "C:\Users\Wesley Scott\Desktop\Pokemon-py-master\game\player.py", line 4, in <module>
    from readchar import readkey
ModuleNotFoundError: No module named 'readchar'

**Comment by Zedwill96** [comment]
realised i have to install dependents XD
